#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DrankVetierApp.Resource", IsApplication=true)]

namespace DrankVetierApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f04001b
			public const int buttonCancel = 2130968603;
			
			// aapt resource value: 0x7f04000c
			public const int buttonCancelIp = 2130968588;
			
			// aapt resource value: 0x7f04000f
			public const int buttonConnect = 2130968591;
			
			// aapt resource value: 0x7f040011
			public const int buttonExtra = 2130968593;
			
			// aapt resource value: 0x7f040000
			public const int buttonGoBack = 2130968576;
			
			// aapt resource value: 0x7f04001c
			public const int buttonIp = 2130968604;
			
			// aapt resource value: 0x7f040024
			public const int buttonMin = 2130968612;
			
			// aapt resource value: 0x7f040012
			public const int buttonOptions = 2130968594;
			
			// aapt resource value: 0x7f040023
			public const int buttonPlus = 2130968611;
			
			// aapt resource value: 0x7f04001e
			public const int buttonSave = 2130968606;
			
			// aapt resource value: 0x7f04000d
			public const int buttonSaveIp = 2130968589;
			
			// aapt resource value: 0x7f040010
			public const int buttonUpdate = 2130968592;
			
			// aapt resource value: 0x7f040006
			public const int editTextIp = 2130968582;
			
			// aapt resource value: 0x7f040027
			public const int editTextName = 2130968615;
			
			// aapt resource value: 0x7f040026
			public const int editTextSpan = 2130968614;
			
			// aapt resource value: 0x7f040020
			public const int editTextWidth = 2130968608;
			
			// aapt resource value: 0x7f040009
			public const int editTextpoort = 2130968585;
			
			// aapt resource value: 0x7f04000e
			public const int linearLayout1 = 2130968590;
			
			// aapt resource value: 0x7f04001a
			public const int linearLayout2 = 2130968602;
			
			// aapt resource value: 0x7f04000a
			public const int linearLayoutButtons = 2130968586;
			
			// aapt resource value: 0x7f040014
			public const int linearLayoutFooter = 2130968596;
			
			// aapt resource value: 0x7f040004
			public const int linearLayoutIp = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int linearLayoutPoort = 2130968583;
			
			// aapt resource value: 0x7f040025
			public const int listViewConfigure = 2130968613;
			
			// aapt resource value: 0x7f040013
			public const int listViewResults = 2130968595;
			
			// aapt resource value: 0x7f040018
			public const int textViewAmount = 2130968600;
			
			// aapt resource value: 0x7f040015
			public const int textViewConnectie = 2130968597;
			
			// aapt resource value: 0x7f040001
			public const int textViewHeader = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int textViewIp = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int textViewIpActivity = 2130968579;
			
			// aapt resource value: 0x7f040017
			public const int textViewLayer = 2130968599;
			
			// aapt resource value: 0x7f040021
			public const int textViewLayers = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int textViewLayersValue = 2130968610;
			
			// aapt resource value: 0x7f040019
			public const int textViewName = 2130968601;
			
			// aapt resource value: 0x7f04001d
			public const int textViewOptionsTitel = 2130968605;
			
			// aapt resource value: 0x7f040008
			public const int textViewPoort = 2130968584;
			
			// aapt resource value: 0x7f040002
			public const int textViewRandom = 2130968578;
			
			// aapt resource value: 0x7f040016
			public const int textViewUpdated = 2130968598;
			
			// aapt resource value: 0x7f04001f
			public const int textViewWidth = 2130968607;
			
			// aapt resource value: 0x7f04000b
			public const int textviewFill = 2130968587;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Extra = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Ip = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Main = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Main_item = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Options = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Options_Item = 2130837509;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			// aapt resource value: 0x7f030009
			public const int buttonCancel = 2130903049;
			
			// aapt resource value: 0x7f030002
			public const int buttonConnect = 2130903042;
			
			// aapt resource value: 0x7f030004
			public const int buttonExtra = 2130903044;
			
			// aapt resource value: 0x7f03000a
			public const int buttonIp = 2130903050;
			
			// aapt resource value: 0x7f03000f
			public const int buttonMin = 2130903055;
			
			// aapt resource value: 0x7f030005
			public const int buttonOptions = 2130903045;
			
			// aapt resource value: 0x7f03000e
			public const int buttonPlus = 2130903054;
			
			// aapt resource value: 0x7f03000b
			public const int buttonSave = 2130903051;
			
			// aapt resource value: 0x7f030003
			public const int buttonUpdate = 2130903043;
			
			// aapt resource value: 0x7f030006
			public const int textViewConnectie = 2130903046;
			
			// aapt resource value: 0x7f030011
			public const int textViewIp = 2130903057;
			
			// aapt resource value: 0x7f030010
			public const int textViewIpActivity = 2130903056;
			
			// aapt resource value: 0x7f03000d
			public const int textViewLayers = 2130903053;
			
			// aapt resource value: 0x7f030001
			public const int textViewMainInfo = 2130903041;
			
			// aapt resource value: 0x7f030008
			public const int textViewOptionsTitel = 2130903048;
			
			// aapt resource value: 0x7f030012
			public const int textViewPoort = 2130903058;
			
			// aapt resource value: 0x7f030007
			public const int textViewUpdated = 2130903047;
			
			// aapt resource value: 0x7f03000c
			public const int textViewWidth = 2130903052;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
