#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TrainTree.Resource", IsApplication=true)]

namespace TrainTree
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040005
			public const int buttonConnect = 2130968581;
			
			// aapt resource value: 0x7f04000b
			public const int buttonToggle = 2130968587;
			
			// aapt resource value: 0x7f040002
			public const int editTextIPAddress = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int editTextIPPort = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int linearLayout1 = 2130968576;
			
			// aapt resource value: 0x7f040007
			public const int textViewDistance = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int textViewGate = 2130968585;
			
			// aapt resource value: 0x7f040001
			public const int textViewIp = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int textViewPoort = 2130968579;
			
			// aapt resource value: 0x7f040008
			public const int textViewSensor = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int textViewServerConnect = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public const int textViewServo = 2130968586;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			// aapt resource value: 0x7f030002
			public const int editTextIp = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int editTextPoort = 2130903043;
			
			// aapt resource value: 0x7f030006
			public const int textViewDistance = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int textViewGate = 2130903047;
			
			// aapt resource value: 0x7f030004
			public const int textViewSensor = 2130903044;
			
			// aapt resource value: 0x7f030001
			public const int textViewServerConnect = 2130903041;
			
			// aapt resource value: 0x7f030005
			public const int textViewServo = 2130903045;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
